service: book-notes-app-api

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-1

  # These environment variables are made available to our functions
  # under process.env.
  environment:
    tableName: books

  # 'iamRoleStatements' defines the permission policy for the Lambda function.
  # In this case Lambda functions are granted with permissions to access DynamoDB.
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:eu-west-1:*:*"

functions:
  #############################################
  ####     Book Management Service         ####
  #############################################

  #############################################
  ####      Book Tracking Service          ####
  #############################################

  #############################################
  ####          Notes Service              ####
  #############################################

  #############################################
  ####         Review Service              ####
  #############################################

  #############################################
  ####    Account Management Service       ####
  #############################################

  #############################################
  ####          Payments Service           ####
  #############################################
  create:
    handler: routes/create.main
    events:
      - http:
          path: books
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: routes/get.main
    events:
      - http:
          path: books/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: routes/list.main
    events:
      - http:
          path: books
          method: get
          cors: true
          authorizer: aws_iam
  update:
    handler: routes/update.main
    events:
      - http:
          path: books/{id}
          method: put
          cors: true
          authorizer: aws_iam
  delete:
    handler: routes/delete.main
    events:
      - http:
          path: books/{id}
          method: delete
          cors: true
          authorizer: aws_iam
# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
