service: book-notes-app-api

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-1
  environment:
    booksTableName: books
    usersTableName: users
    transactionsTableName: transactions
    timeSeriesTableName: bookNotes_timeSeries
    googleBooksKey: ${env:GOOGLE_KEY}
    stripeSecretKey: ${env:STRIPE_SECRET_KEY}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'
    - Effect: 'Allow'
      Action:
        - SES:SendEmail
        - SES:SendRawEmail
      Resource: '*'

functions:
  #############################################
  ####      User Management Service        ####
  #############################################
  #############################################
  ####     Book Management Service         ####
  #############################################
  #############################################
  ####          Notes Service              ####
  #############################################
  #############################################
  ####         Review Service              ####
  #############################################
  #############################################
  ####      Book Tracking Service          ####
  #############################################
  #############################################
  ####     TimeSeries Tracking Service     ####
  #############################################
  #############################################
  ####          Payments Service           ####
  #############################################
  #############################################
  ####           Emails Service            ####
  #############################################

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
