service: liberead-users

package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-domain-manager

custom:
  customDomain:
    domainName: api.liberead.com
    basePath: users
    stage: prod
    createRoute53Record: true
  dotenv:
    path: ../../.env

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-1
  environment:
    booksTableName: books
    usersTableName: users
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:eu-west-1:*:*'

functions:
  createUser:
    handler: services/createUser.main
    events:
      - http:
          path: /
          method: post
          cors: true
          authorizer: aws_iam
  getUser:
    handler: services/getUser.main
    events:
      - http:
          path: /
          method: get
          cors: true
          authorizer: aws_iam
  updateUser:
    handler: services/updateUser.main
    events:
      - http:
          path: /
          method: put
          cors: true
          authorizer: aws_iam

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(../resources/api-gateway-errors.yml)}
